---
title: "Machine Learning Debt"
subtitle: "Journal Club"
# author: "David Dai"
date: "2019/03/07"
output:
  xaringan::moon_reader:
    # css: [default, default-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      titleSlideClass: ["bottom", "left", "my-title"]
      countIncrementalSlides: false

---



# .center["Real world software engineers are often faced with the challenge of moving quickly to ship new products or services, which can lead to a dilemma between *speed of execution* and *quality of engineering*."]

---

# Technical Debt

## Cost of the "speed vs. quality" tradeoff

* Convenient methods promote speed of development
* However, these methods tend to create compounding debt as the system grows in complexity

## Not all debt is bad
* Debt may be necessary in certain situations, especially in initial development of systems
 
* Important to be aware of sources of technical debt, as costs tend to compound with additional debt


---

# From a traditional software engineering perspective...

## Technical debt can be paid off by

* Refactoring code, deleting dead code
* Improved unit testing
* Improved documentation
* Reducing dependencies

## The goal is NOT to add new functionality, but to improve the system (ease of future development/maintenance and reduction of bugs)

---

# From a machine learning (or modelling, more generally) perspective...



---

# Complexities in machine learning systems

---

# System dependencies

---

# Data dependencies

---

# Real-world dependencies

---

# Monitoring and testing of systems

---

